// Please use the following editor setup for this file:
// Tab size=2; Tabs as spaces; Clean up trailing whitepsace
//
// In vim add: au FileType proto setl sw=2 ts=2 expandtab list
//
// In vscode install vscode-proto3 extension and add this to your settings.json:
//    "[proto3]": {
//        "editor.tabSize": 2,
//        "editor.insertSpaces": true,
//        "editor.rulers": [80],
//        "editor.detectIndentation": true,
//        "files.trimTrailingWhitespace": true
//    }
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: public/portworx/pds/deploymentevents/apiv1/deploymentevents.proto

package deploymentevent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DeploymentEventService_ListDeploymentEvents_FullMethodName = "/public.portworx.pds.deploymentevents.v1.DeploymentEventService/ListDeploymentEvents"
)

// DeploymentEventServiceClient is the client API for DeploymentEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeploymentEventServiceClient interface {
	// ListDeploymentEvents API returns the list of kubernetes events related to a deployment.
	ListDeploymentEvents(ctx context.Context, in *ListDeploymentEventsRequest, opts ...grpc.CallOption) (*ListDeploymentEventsResponse, error)
}

type deploymentEventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeploymentEventServiceClient(cc grpc.ClientConnInterface) DeploymentEventServiceClient {
	return &deploymentEventServiceClient{cc}
}

func (c *deploymentEventServiceClient) ListDeploymentEvents(ctx context.Context, in *ListDeploymentEventsRequest, opts ...grpc.CallOption) (*ListDeploymentEventsResponse, error) {
	out := new(ListDeploymentEventsResponse)
	err := c.cc.Invoke(ctx, DeploymentEventService_ListDeploymentEvents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeploymentEventServiceServer is the server API for DeploymentEventService service.
// All implementations must embed UnimplementedDeploymentEventServiceServer
// for forward compatibility
type DeploymentEventServiceServer interface {
	// ListDeploymentEvents API returns the list of kubernetes events related to a deployment.
	ListDeploymentEvents(context.Context, *ListDeploymentEventsRequest) (*ListDeploymentEventsResponse, error)
	mustEmbedUnimplementedDeploymentEventServiceServer()
}

// UnimplementedDeploymentEventServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDeploymentEventServiceServer struct {
}

func (UnimplementedDeploymentEventServiceServer) ListDeploymentEvents(context.Context, *ListDeploymentEventsRequest) (*ListDeploymentEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeploymentEvents not implemented")
}
func (UnimplementedDeploymentEventServiceServer) mustEmbedUnimplementedDeploymentEventServiceServer() {
}

// UnsafeDeploymentEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeploymentEventServiceServer will
// result in compilation errors.
type UnsafeDeploymentEventServiceServer interface {
	mustEmbedUnimplementedDeploymentEventServiceServer()
}

func RegisterDeploymentEventServiceServer(s grpc.ServiceRegistrar, srv DeploymentEventServiceServer) {
	s.RegisterService(&DeploymentEventService_ServiceDesc, srv)
}

func _DeploymentEventService_ListDeploymentEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeploymentEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentEventServiceServer).ListDeploymentEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentEventService_ListDeploymentEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentEventServiceServer).ListDeploymentEvents(ctx, req.(*ListDeploymentEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeploymentEventService_ServiceDesc is the grpc.ServiceDesc for DeploymentEventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeploymentEventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "public.portworx.pds.deploymentevents.v1.DeploymentEventService",
	HandlerType: (*DeploymentEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDeploymentEvents",
			Handler:    _DeploymentEventService_ListDeploymentEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public/portworx/pds/deploymentevents/apiv1/deploymentevents.proto",
}
